module.exports = `-- MySQL Script generated by MySQL Workbench
  -- Sun Jun 23 01:45:56 2019
  -- Model: New Model    Version: 1.0
  -- MySQL Workbench Forward Engineering

  SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
  SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
  SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

  -- -----------------------------------------------------
  -- Schema eshop
  -- -----------------------------------------------------

  -- -----------------------------------------------------
  -- Schema eshop
  -- -----------------------------------------------------
  CREATE SCHEMA IF NOT EXISTS eshop DEFAULT CHARACTER SET utf8 ;
  USE eshop ;

  -- -----------------------------------------------------
  -- Table eshop.catalog
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.catalog (
    product_id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(45) NOT NULL,
    price_netto DECIMAL(10,2) NOT NULL,
    price_brutto DECIMAL(10,2) NOT NULL,
    price_old_netto DECIMAL(10,2) NOT NULL,
    price_old_brutto DECIMAL(10,2) NOT NULL,
    vat_percent INT NOT NULL,
    stock INT NOT NULL,
    description VARCHAR(45) NULL,
    PRIMARY KEY (product_id))
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.users
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.users (
    user_id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(45) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(45) NOT NULL,
    role INT NULL,
    PRIMARY KEY (user_id),
    UNIQUE INDEX email_UNIQUE (email ASC),
    UNIQUE INDEX login_UNIQUE (username ASC))
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.orders
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.orders (
    order_id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    status VARCHAR(45) NOT NULL,
    created_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    total_price_netto DECIMAL(10,2) NOT NULL,
    total_price_brutto DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (order_id),
    INDEX fk_transactions_users1_idx (user_id ASC),
    CONSTRAINT fk_transactions_users1
      FOREIGN KEY (user_id)
      REFERENCES eshop.users (user_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.order_items
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.order_items (
    order_item_id INT NOT NULL,
    product_id INT NOT NULL,
    transation_id INT NOT NULL,
    quantity INT NOT NULL,
    price_netto DECIMAL(10,2) NOT NULL,
    price_brutto DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (order_item_id),
    INDEX fk_transaction_items_catalog1_idx (product_id ASC),
    INDEX fk_transaction_items_transactions1_idx (transation_id ASC),
    CONSTRAINT fk_transaction_items_catalog1
      FOREIGN KEY (product_id)
      REFERENCES eshop.catalog (product_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT fk_transaction_items_transactions1
      FOREIGN KEY (transation_id)
      REFERENCES eshop.orders (order_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.categories
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.categories (
    category_id INT NOT NULL AUTO_INCREMENT,
    category_name VARCHAR(45) NOT NULL,
    category_path VARCHAR(45) NOT NULL,
    PRIMARY KEY (category_id))
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.producers
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.producers (
    producer_id INT NOT NULL,
    producer_name VARCHAR(45) NOT NULL,
    producer_path VARCHAR(45) NOT NULL,
    PRIMARY KEY (producer_id))
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.invoices
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.invoices (
    invoice_id INT NOT NULL,
    user_id INT NOT NULL,
    invoice_number VARCHAR(45) NOT NULL,
    date_of_sale DATETIME NOT NULL,
    total_price_netto DECIMAL(10,2) NOT NULL,
    total_price_brutto DECIMAL(10,2) NOT NULL,
    total_vat_value DECIMAL(10,2) NOT NULL,
    bank_name VARCHAR(90) NULL,
    payment_method VARCHAR(45) NOT NULL,
    PRIMARY KEY (invoice_id),
    INDEX fk_invoices_users1_idx (user_id ASC),
    CONSTRAINT fk_invoices_users1
      FOREIGN KEY (user_id)
      REFERENCES eshop.users (user_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.invoice_items
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.invoice_items (
    ivoice_item_id INT NOT NULL,
    invoice_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    vat_value DECIMAL(10,2) NOT NULL,
    price_netto DECIMAL(10,2) NOT NULL,
    price_brutto DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ivoice_item_id),
    INDEX fk_invoice_items_invoices1_idx (invoice_id ASC),
    INDEX fk_invoice_items_catalog1_idx (product_id ASC),
    CONSTRAINT fk_invoice_items_invoices1
      FOREIGN KEY (invoice_id)
      REFERENCES eshop.invoices (invoice_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT fk_invoice_items_catalog1
      FOREIGN KEY (product_id)
      REFERENCES eshop.catalog (product_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.contacts
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.contacts (
    contact_id INT NOT NULL,
    user_id INT NOT NULL,
    name VARCHAR(45) NULL,
    surname VARCHAR(45) NULL,
    company_name VARCHAR(45) NULL,
    nip VARCHAR(45) NULL,
    regon VARCHAR(45) NULL,
    phone_number_1 VARCHAR(45) NULL,
    phone_number_2 VARCHAR(45) NULL,
    fax VARCHAR(45) NULL,
    www VARCHAR(45) NULL,
    PRIMARY KEY (contact_id),
    INDEX fk_contacts_users1_idx (user_id ASC),
    CONSTRAINT fk_contacts_users1
      FOREIGN KEY (user_id)
      REFERENCES eshop.users (user_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.addresses
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.addresses (
    address_id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    location VARCHAR(45) NULL,
    voivodeship VARCHAR(45) NULL,
    postal_code VARCHAR(8) NULL,
    street_name VARCHAR(45) NULL,
    street_number VARCHAR(8) NULL,
    number_of_premises VARCHAR(8) NULL,
    PRIMARY KEY (address_id),
    INDEX fk_addresses_users1_idx (user_id ASC),
    CONSTRAINT fk_addresses_users1
      FOREIGN KEY (user_id)
      REFERENCES eshop.users (user_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.pictures
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.pictures (
    picture_id INT NOT NULL AUTO_INCREMENT,
    product_id INT NOT NULL,
    description TEXT NOT NULL,
    path VARCHAR(100) NOT NULL,
    label INT NOT NULL,
    PRIMARY KEY (picture_id),
    INDEX fk_pictures_catalog1_idx (product_id ASC),
    CONSTRAINT fk_pictures_catalog1
      FOREIGN KEY (product_id)
      REFERENCES eshop.catalog (product_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  -- -----------------------------------------------------
  -- Table eshop.categories_producers
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS eshop.categories_producers (
    categories_producers_id INT NOT NULL,
    producer_id INT NOT NULL,
    category_id INT NOT NULL,
    product_id INT NOT NULL,
    PRIMARY KEY (categories_producers_id),
    INDEX fk_categories_producers_producers1_idx (producer_id ASC),
    INDEX fk_categories_producers_categories1_idx (category_id ASC),
    INDEX fk_categories_producers_catalog1_idx (product_id ASC),
    CONSTRAINT fk_categories_producers_producers1
      FOREIGN KEY (producer_id)
      REFERENCES eshop.producers (producer_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT fk_categories_producers_categories1
      FOREIGN KEY (category_id)
      REFERENCES eshop.categories (category_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
    CONSTRAINT fk_categories_producers_catalog1
      FOREIGN KEY (product_id)
      REFERENCES eshop.catalog (product_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


  SET SQL_MODE=@OLD_SQL_MODE;
  SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
  SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
  `;
